# Generated by Django 6.1.1 on 2026-10-08 01:23

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], max_length=10)),
            ],
            options={
                'db_table': 'breed',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('idOwner', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'owner',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'disease',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('isDeleted', False)), name='unique_active_disease_name_case_insensitive')],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('idMedication', models.AutoField(db_column='idMedication', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dose', models.DecimalField(decimal_places=3, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medication',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('dose'), condition=models.Q(('isDeleted', False)), name='unique_active_medication_case_insensitive')],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthDate', models.DateField()),
                ('neutered', models.BooleanField(default=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo', models.URLField(blank=True, null=True)),
                ('idOwner', models.PositiveIntegerField(help_text='ID del dueño asignado por el módulo Owner')),
                ('isDeleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='api.breed')),
            ],
            options={
                'db_table': 'pet',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('isDeleted', False)), fields=('idOwner', 'name', 'breed', 'birthDate'), name='unique_active_pet_per_owner')],
            },
        ),
    ]
