# Generated by Django 6.1.1 on 2026-10-03 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], max_length=10)),
            ],
            options={
                'db_table': 'breed',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'owner',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthDate', models.DateField()),
                ('neutered', models.BooleanField(default=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo', models.URLField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='api.breed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='api.owner')),
            ],
            options={
                'db_table': 'pet',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('isDeleted', False)), fields=('owner', 'name', 'breed', 'birthDate'), name='unique_active_pet_per_owner')],
            },
        ),
    ]
