# Generated by Django 6.1.1 on 2026-10-04 04:47

import api.models.medical_test
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_seed_breeds"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalTest",
            fields=[
                (
                    "idMedicalTest",
                    models.AutoField(
                        db_column="idMedicalTest", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("laboratory", "Laboratorio"),
                            ("imaging", "Imagen"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "veterinarian",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("altered", "Alterado"),
                            ("pending", "Pendiente"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resultSummary",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "resultDetail",
                    models.TextField(blank=True, default="", max_length=2000),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=api.models.medical_test.medical_test_upload_path,
                    ),
                ),
                ("isDeleted", models.BooleanField(default=False)),
                (
                    "pet",
                    models.ForeignKey(
                        db_column="idPet",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medicalTests",
                        to="api.pet",
                    ),
                ),
            ],
            options={
                "db_table": "medical_test",
                "ordering": ["-date", "-idMedicalTest"],
            },
        ),
    ]
