# Generated by Django 6.1.1 on 2026-10-06 02:24

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_seed_diseases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('idMedication', models.AutoField(db_column='idMedication', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dose', models.DecimalField(decimal_places=3, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medication',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('dose'), condition=models.Q(('isDeleted', False)), name='unique_active_medication_case_insensitive')],
            },
        ),
    ]
