# Generated by Django 6.1.1 on 2026-10-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seed_medications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['name']},
        ),
    ]
