# Generated by Django 6.1.1 on 2026-10-09 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencyHours', models.IntegerField(db_column='frequencyHours')),
                ('quantityDose', models.IntegerField(db_column='quantityDose')),
                ('startDate', models.DateField(db_column='startDate')),
                ('notes', models.TextField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(db_column='idMedication', on_delete=django.db.models.deletion.PROTECT, related_name='pet_treatments', to='api.medication')),
                ('pet', models.ForeignKey(db_column='idPet', on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='api.pet')),
            ],
            options={
                'db_table': 'medication_pet',
                'ordering': ['-startDate', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('isDeleted', False)), fields=('pet', 'medication'), name='unique_active_medication_per_pet')],
            },
        ),
    ]
