# Generated by Django 6.1.1 on 2026-10-09 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('disease', models.ForeignKey(db_column='idDisease', on_delete=django.db.models.deletion.PROTECT, related_name='pet_cases', to='api.disease')),
                ('pet', models.ForeignKey(db_column='idPet', on_delete=django.db.models.deletion.PROTECT, related_name='diseases', to='api.pet')),
            ],
            options={
                'db_table': 'pet_disease',
                'ordering': ['-startDate', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('endDate__isnull', True), ('isDeleted', False)), fields=('pet', 'disease'), name='unique_active_disease_per_pet'), models.UniqueConstraint(condition=models.Q(('isDeleted', False)), fields=('pet', 'disease', 'startDate'), name='unique_pet_disease_start_date')],
            },
        ),
    ]
