# Generated by Django 6.1.1 on 2026-10-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_medication_pet'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicationpet',
            name='unique_active_medication_per_pet',
        ),
        migrations.AddField(
            model_name='medicationpet',
            name='endDate',
            field=models.DateField(blank=True, db_column='endDate', null=True),
        ),
        migrations.AddConstraint(
            model_name='medicationpet',
            constraint=models.UniqueConstraint(condition=models.Q(('endDate__isnull', True), ('isDeleted', False)), fields=('pet', 'medication'), name='unique_active_medication_per_pet'),
        ),
        migrations.AddConstraint(
            model_name='medicationpet',
            constraint=models.UniqueConstraint(condition=models.Q(('isDeleted', False)), fields=('pet', 'medication', 'startDate'), name='unique_pet_medication_start_date'),
        ),
    ]
