services:

  db:
    image: postgres:18
    container_name: agiles_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: agiles_api
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  web:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: agiles_web
    restart: unless-stopped
    command: sh -c "npm install && npm run start -- --lan"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "8081:8081"
      - "8082:8082"
      - "19000:19000"
    depends_on:
      - api

volumes:
  postgres_data: